### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by mdavis-xyz** [aguinane/nem-reader#30]
# Steps to reproduce

* Python 3.8.11
* create a virtual environment `python3 -m venv ~/nemreader-venv`
* `. ~/nemreader-venv/bin/activate`
* `pip install nemreader[cli]`
* download sample: `curl "https://github.com/aguinane/nem-reader/raw/master/examples/nem12/NEM12%23000000000000001%23CNRGYMDP%23NEMMCO.zip" > test.zip`
* process it with the cli: `nemreader output-csv test.zip `

# expected behavior

File is processed, no errors thrown, new file generated

# Actual behavior

```
Traceback (most recent call last):
  File "/home/ec2-user/nemreader-venv/bin/nemreader", line 5, in <module>
    from nemreader.cli import cli
  File "/home/ec2-user/nemreader-venv/lib/python3.8/site-packages/nemreader/__init__.py", line 12, in <module>
    from .nem_reader import read_nem_file, parse_nem_file
  File "/home/ec2-user/nemreader-venv/lib/python3.8/site-packages/nemreader/nem_reader.py", line 15, in <module>
    from .nem_objects import (B2BDetails12, B2BDetails13, BasicMeterData,
  File "/home/ec2-user/nemreader-venv/lib/python3.8/site-packages/nemreader/nem_objects.py", line 11, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'
```

I'm not sure why this is, given that `pydantic` is in the requirements.txt.
Is the issue that pydantic doesn't appear in `install_requires` in `setup.cfg`?

After manually doing `pip install pydantic`, I get:

```
Traceback (most recent call last):
  File "/home/ec2-user/nemreader-venv/bin/nemreader", line 5, in <module>
    from nemreader.cli import cli
ImportError: cannot import name 'cli' from 'nemreader.cli' (/home/ec2-user/nemreader-venv/lib/python3.8/site-packages/nemreader/cli.py)
```

Now I'm stuck.

Also, [the installation docs](https://nem-reader.readthedocs.io/en/latest/installation.html) say `pip install nemreader[cli]` twice. Is the first one supposed to *not* have the `[cli]` part?

**Comment by mdavis-xyz** [comment]
I've just checked, yes `install_requires` fixes the first of the two issues.

**Comment by aguinane** [comment]
This should be fixed now.

**Comment by mdavis-xyz** [comment]
It looks like the latest version on pypi is from september. That still gives the same behavior.

When I test from the master branch, I get:

```
Traceback (most recent call last):
  File "/home/ec2-user/.pyenv/versions/3.8.11/bin/nemreader", line 33, in <module>
    sys.exit(load_entry_point('nemreader', 'console_scripts', 'nemreader')())
  File "/home/ec2-user/.pyenv/versions/3.8.11/bin/nemreader", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/ec2-user/.pyenv/versions/3.8.11/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/ec2-user/.pyenv/versions/3.8.11/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ec2-user/environment/scratch/nemreaderdeps/repo/nemreader/cli.py", line 6, in <module>
    import typer
ModuleNotFoundError: No module named 'typer'
```

**Comment by mdavis-xyz** [comment]
I see `typer` in requirements.txt but not setup.cfg.

What's the difference between those two?

**Comment by aguinane** [comment]
Yep same issue as last time. Unfortunately, they can't be in the one spot as pip uses a different file format depending on whether you are publishing a library or using it (for unit tests etc) - it is a bit annoying.

**Comment by mdavis-xyz** [comment]
Hmm, I haven't encountered any other library that has two requirements lists. Has setup.cfg been superseded with setup.py? That way set-up.py can just read the requirements.txt file.

**Comment by aguinane** [comment]
setup.py was replaced with setup.cfg and now pyproject.toml. 
https://packaging.python.org/en/latest/flow/#the-configuration-file

So they should actually be in the pyproject.toml file not setup.cfg - I'll move it.

**Comment by aguinane** [comment]
Looks like you can use `pip-compile --all-extras --resolver=backtracking pyproject.toml` to generate the requirements from the pyproject.toml so will do that from now on.
